name = "VMLS"
uuid = "44dac47c-a70e-11e8-3cff-fbf5f1f7c554"
license = "MIT"
authors = ["Stephen Boyd <boyd@stanford.edu>", "Lieven Vandenberghe <vandenbe@ucla.edu"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
